---
- name: load ~/.bashrc from ~/.bash_profile
  lineinfile:
    path: ~/.bash_profile
    line: "if [ -f ~/.bashrc ]; then . ~/.bashrc; fi"

- name: read /etc/shells
  register: etc_shells
  shell: cat /etc/shells

- name: add homebrew bash shell
  shell: echo "/opt/homebrew/bin/bash" | sudo tee -a /etc/shells
  when: "'/opt/homebrew/bin/bash' not in etc_shells.stdout"

- name: get the current shell
  shell: echo $SHELL
  register: current_shell

- name: default to the homebrew bash shell
  shell: chsh -s /opt/homebrew/bin/bash
  when: current_shell.stdout != "/opt/homebrew/bin/bash"

- name: create ~/.bash
  file:
    path: ~/.bash
    state: directory

- name: download .git-completion.bash
  get_url:
    url: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
    dest: ~/.bash/.git-completion.bash

- name: create ~/dev
  file:
    path: ~/dev
    state: directory

- name: clone dotfiles repo
  git:
    repo: git@github.com:bmealhouse/dotfiles.git
    dest: ~/dev/dotfiles

- name: create a symbolic link for .bashrc
  file:
    src: ~/dev/dotfiles/bash/.bashrc
    dest: ~/.bashrc
    state: link

- name: create a symbolic link for neovim
  file:
    src: ~/dev/dotfiles/nvim
    dest: ~/.config/nvim
    state: link
