---
- include_vars: vars/ssh.yml

- name: ensure the ~/.ssh directory exists
  file:
    path: ~/.ssh
    state: directory

- name: generate an OpenSSH keypair for GitHub access
  register: ssh_key
  community.crypto.openssh_keypair:
    path: ~/.ssh/github_ed25519
    type: ed25519
    comment: bmealhouse@gmail.com

- name: authorize SSH key with GitHub
  community.general.github_key:
    name: Brent's MacBook Pro (BILL)
    token: "{{ github_access_token }}"
    pubkey: "{{ ssh_key.public_key }} {{ ssh_key.comment }}"
    state: present

- name: generate an OpenSSH keypair for GitLab access
  register: ssh_key
  community.crypto.openssh_keypair:
    path: ~/.ssh/gitlab_bill_ed25519
    type: ed25519
    comment: brent.mealhouse@hq.bill.com
