---
- hosts: all

  tasks:
    - import_tasks: tasks/ssh-work.yml
      tags:
        - ssh
    - import_tasks: tasks/git-work.yml
      tags:
        - git
    - import_tasks: tasks/system.yml
      tags:
        - system
        - up
    - import_tasks: tasks/homebrew-work.yml
      tags:
        - brew
        - up
    - import_tasks: tasks/node-work.yml
      tags:
        - node
        - up
    - import_tasks: tasks/dotfiles-work.yml
      tags:
        - dotfiles
        - up
    - import_tasks: tasks/fonts.yml
      tags:
        - fonts
        - up
